---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

trasport:
  name: winrm
  elevated: true
  elevated_username: vagrant
  elevated_password: vagrant

platforms:
  - name: windows2012r2

suites:
  - name: default
    run_list:
      - recipe[chef_test_5::default]
