name 'chef_task_5'
maintainer 'Alex Dzyubenko'
maintainer_email 'zzzdzuba@gmail.com'
license 'all_rights'
description 'Installs/Configures chef_task_5'
long_description 'Installs/Configures chef_task_5'
version '0.1.0'
issues_url 'https://github.com/DZUBA/chef_test_5'
source_url 'https://github.com/DZUBA/chef_test_5'

depends 'windows', '~> 2.1.1'
